//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarhatniyeBrovki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        static Service sv;

        public static Service CreateEmployee(int Id, string Title, decimal Cost, int DurationInSeconds, string Description, double Discount, string MainImagePath)
        {
            sv = new Service();
            sv.ID = Id;
            sv.Title = Title;
            sv.Cost = Cost;
            sv.DurationInSeconds = DurationInSeconds;
            sv.Description = Description;
            sv.Discount = Discount;
            sv.MainImagePath = MainImagePath;
            return sv;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ClientServices = new HashSet<ClientService>();
            this.ServicePhotoes = new HashSet<ServicePhoto>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public decimal Cost { get; set; }
        public int DurationInSeconds { get; set; }
        public string Description { get; set; }
        public Nullable<double> Discount { get; set; }
        public string MainImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhotoes { get; set; }
    }
}
